### PR TITLE
Array and union fix

### PR DESCRIPTION
**Pull request by AG92**
Fix for unions and array-constraints.

### CODE REVIEW

**Comment by attah** [comment]
Bump :)

**Comment by kevinrenskers** [comment]
I've taken a look at this, and I am not really convinced that these changes are for the best.

Old:
screen shot 2019-01-28 at 15 29 47

New:
screen shot 2019-02-12 at 12 09 50

My problem is that getting rid of the parenthesis everywhere makes it less readable. And the inline expansion of the union types, while useful, I think can be done in a better way without cluttering up the screen so much. I think this is too much info presented in not a very useful way. I'd probably prefer some kind of popup: the `cat` and `dog` types would be links, clicking them opens their information. Rather then all this information being presented like this, making it hard to see what belongs to what, etc.

So yeah I'm sorry but I don't think I want to merge this in its current state.

**Comment by kevinrenskers** [comment]
Sorry about that wrong screenshot, people who got it in their email :)

**Comment by attah** [comment]
I agree breaking out unions to bullet lists doesn't look as snazzy as inside parenthesis, especially for primitives. Since there can be unions of primitives and objects as well, that seemed like a reasonable solution at the time. It does get a bit lengthy, but it sure is better than no docs at all for Cat and Dog. Seems one can stack modals, so i guess that popup types could work. Doesn't this mean objects in arrays are also too "cluttered" and should be considered for moving to their own popups too? What about examples?

One problem we have is that it is quite hard to get an overview of the entire API, which is especially painful for reviewing. Modals certainly doesn't help with that. Maybe one could cook up something where the user can either go full modal, or expand everything on the current+lower levels... Seems i need a bootstrap intern...

**Comment by kevinrenskers** [comment]
Maybe a sidebar on the right side of the modal, where these expanded types can be shown? So on the left is the main info, as it is now, then on the right you'd see the "extra" info. Not sure if that would be better, how it would look, but something to maybe explore.

**Comment by attah** [comment]
Hmm, yeah, i think he default Swagger doc thingy has "all types" somewhere, and which you can get anchor-linked into. It doesn't solve my wish for a expand-all view, but indeed worth exploring.

**Pull request closed without merging**
