### PR TITLE
Make it easier to notice required fields and default values:smiley:

### PR DESCRIPTION
**Pull request by Ahimta**

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Thanks for the PR. Can you add before/after screenshots? Thanks!

**Comment by Ahimta** [comment]
## Before

before

## After

after

**Comment by kevinrenskers** [comment]
Ok, I like the red color for the `required` keyword. However, I don't like the style for the default values, and I don't like the `font-style` change to `required` either. So, can you just keep the red color change, and that's it?

**Comment by Ahimta** [comment]
Only the color for required is changed now:smiley:.

**Comment by Ahimta** [comment]
Can't wait to see it in the next `raml2html` release:smiley:.

**Comment by kevinrenskers** [comment]
It’s already released. But it’s not a raml2html update; its an update of the default theme. Small but important difference :)
When you update your npm packages, it’ll be updated.

**Pull request merged**
